### ISSUE TITLE
Override cwd that yarn runs with

### ISSUE THREAD

**Issue by recurrence** [jonschlinkert/yarn-api#2]
It would be great to be able to specify where yarn's current working directory is.  In particular, I want to run yarn operations in a different place altogether from where the yarn module is being invoked.

I can send a PR for that; I was curious if you had a preference for how that would work?

**Comment by recurrence** [comment]
Nevermind, Yarn *just* added cwd this week :) https://github.com/yarnpkg/website/issues/651

**Comment by jonschlinkert** [comment]
I was about to reply, I wasn't aware of that. thanks!
